
SELECT TB1.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE) AS TOTAL_SALES FROM (
SELECT  A.BOOK_ID, CATEGORY,  AUTHOR_ID, (B.PRICE*A.SALES) AS PRICE FROM BOOK_SALES A
JOIN BOOK B ON (A.BOOK_ID = B.BOOK_ID)
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1) TB1
JOIN AUTHOR TB2 ON TB1.AUTHOR_ID = TB2.AUTHOR_ID
GROUP BY TB1.AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY TB1.AUTHOR_ID ASC , CATEGORY DESC