
SELECT ID, IF(TB2.CHILD_COUNT IS NOT NULL, TB2.CHILD_COUNT, 0) AS CHILD_COUNT FROM ECOLI_DATA  TB1
LEFT JOIN (SELECT PARENT_ID, COUNT(PARENT_ID) AS CHILD_COUNT FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL GROUP BY PARENT_ID) TB2 
ON TB1.ID = TB2.PARENT_ID
ORDER BY ID 