# SELECT YEAR,MONTH,GENDER, COUNT(DISTINCT USER_ID) AS USERS FROM (
# SELECT DATE_FORMAT(SALES_DATE,'%Y')AS YEAR,DATE_FORMAT(SALES_DATE,'%c')AS MONTH, USER_INFO.USER_ID,USER_INFO.GENDER FROM ONLINE_SALE INNER JOIN USER_INFO ON ONLINE_SALE.USER_ID = USER_INFO.USER_ID)A WHERE A.GENDER IS NOT NULL
# GROUP BY YEAR, MONTH, GENDER
# ORDER BY YEAR, MONTH, GENDER

SELECT 
  YEAR(A.SALES_DATE) AS YEAR, MONTH(A.SALES_DATE) AS MONTH, B.GENDER,
  COUNT(DISTINCT A.USER_ID) AS USERS
FROM ONLINE_SALE A
JOIN USER_INFO B ON A.USER_ID = B.USER_ID
WHERE B.GENDER IS NOT NULL
GROUP BY YEAR(A.SALES_DATE), MONTH(A.SALES_DATE), B.GENDER
ORDER BY YEAR, MONTH, B.GENDER;