# 0이면 남자
# 1이면 여자


# SELECT * FROM USER_INFO WHERE YEAR(JOINED)='2021';

# SELECT * FROM (SELECT * FROM USER_INFO WHERE YEAR(JOINED)='2021') A
# JOIN ONLINE_SALE B USING(USER_ID) 
# ORDER BY USER_ID

# SELECT  YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_ID, JOINED, SALES_DATE 
# FROM (SELECT * FROM USER_INFO WHERE YEAR(JOINED)='2021') A
# JOIN ONLINE_SALE B USING(USER_ID) 


# SELECT *,COUNT(USER_ID) FROM (
# SELECT  YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_ID, JOINED, SALES_DATE 
# FROM (SELECT * FROM USER_INFO WHERE YEAR(JOINED)='2021') A
# JOIN ONLINE_SALE B USING(USER_ID) ) C GROUP BY YEAR,MONTH, USER_ID
# ORDER BY YEAR, MONTH, USER_ID


SELECT YEAR, MONTH, PURCHASED_USERS, ROUND(PURCHASED_USERS/K,1) AS PUCHASED_RATIO FROM (
SELECT YEAR,MONTH,COUNT(USER_ID) AS PURCHASED_USERS FROM (
SELECT * FROM (
SELECT  YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_ID
FROM (SELECT * FROM USER_INFO WHERE YEAR(JOINED)='2021') A
JOIN ONLINE_SALE B USING(USER_ID) ) C GROUP BY YEAR,MONTH, USER_ID) D
GROUP BY YEAR,MONTH) E
JOIN (SELECT COUNT(*) AS K FROM USER_INFO WHERE YEAR(JOINED)='2021') F
ORDER BY YEAR ASC, MONTH ASC