
SELECT A.PRODUCT_ID, PRODUCT_NAME, (PRICE*K) AS TOTAL_SALES FROM 
(SELECT * FROM FOOD_PRODUCT) A
INNER JOIN 
(SELECT PRODUCT_ID, PRODUCE_DATE, SUM(AMOUNT) AS K FROM FOOD_ORDER WHERE LEFT(PRODUCE_DATE,7)='2022-05' GROUP BY PRODUCT_ID) B
WHERE A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC