

# SELECT A.FLAVOR FROM ( SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS S1 FROM FIRST_HALF GROUP BY FLAVOR) A
# JOIN ( SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS S2 FROM JULY GROUP BY FLAVOR ) B
# GROUP BY FLAVOR
# ORDER BY S1+S2 DESC
# LIMIT 3

# SELECT C.FLAVOR, C.T1, C.T2, C.T1+C.T2 AS TOTAL_PRICE FROM (
# SELECT A.FLAVOR, SUM(S1) T1, SUM(S2) T2 FROM ( SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS S1 FROM FIRST_HALF GROUP BY FLAVOR) A
# JOIN ( SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS S2 FROM JULY GROUP BY FLAVOR ) B
# GROUP BY A.FLAVOR)C
# ORDER BY (C.T1+C.T2) DESC
# LIMIT 3

SELECT C.FLAVOR FROM (
SELECT FLAVOR, SUM(TOTAL_ORDER) AS S1 FROM JULY GROUP BY FLAVOR
UNION
SELECT FLAVOR, SUM(TOTAL_ORDER) AS S1 FROM FIRST_HALF GROUP BY FLAVOR
) C GROUP BY C.FLAVOR 
ORDER BY SUM(C.S1) DESC
LIMIT 3