-- 코드를 입력하세요

# MDDR_ID 의사 ID

# PT_NAME
SELECT APNT_NO,PT_NAME,TB1.PT_NO, MCDP_CD, DR_NAME, APNT_YMD FROM (
SELECT APNT_NO, PT_NO, APPOINTMENT.MCDP_CD, DR_NAME, APNT_YMD from APPOINTMENT 
JOIN DOCTOR
ON APPOINTMENT.MDDR_ID = DOCTOR.DR_ID
where DATE(APNT_YMD) = '2022-04-13' AND APNT_CNCL_YN = 'N'AND APPOINTMENT.MCDP_CD = 'CS') TB1
JOIN PATIENT TB2 ON TB1.PT_NO = TB2.PT_NO
ORDER BY APNT_YMD ASC
