# SELECT * FROM HR_DEPARTMENT
# SELECT * FROM HR_EMPLOYEES 
# SELECT * FROM HR_GRADE 

SELECT EMP_NO, EMP_NAME, GRADE, IF(GRADE='S',SAL*0.2,IF(GRADE='A',SAL*0.15, IF(GRADE='B',SAL*0.1,SAL*0))) AS BONUS FROM (
SELECT EMP_NO, EMP_NAME, DEPT_ID, POSITION, SAL, YEAR, IF(SCORE>=96,'S',IF(SCORE>=90,'A',IF(SCORE>=80,'B','C'))) AS GRADE FROM (
SELECT EMP_NO, EMP_NAME, DEPT_ID, POSITION, SAL, YEAR, AVG(SCORE) AS SCORE FROM HR_EMPLOYEES JOIN HR_GRADE USING(EMP_NO) GROUP BY EMP_NO) TB1 ) TB2
ORDER BY EMP_NO

