SELECT DISTINCT A.CAR_ID AS CAR_ID FROM ((
SELECT * FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE = "세단") AS A
INNER JOIN  (SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE LEFT(START_DATE,7)="2022-10") AS B
ON A.CAR_ID = B.CAR_ID)
ORDER BY A.CAR_ID DESC
