SELECT ID, FISH_NAME, LENGTH FROM FISH_INFO TB1 JOIN FISH_NAME_INFO USING (FISH_TYPE)
WHERE LENGTH IS NOT NULL AND LENGTH IN (SELECT MAX(LENGTH) FROM FISH_INFO WHERE LENGTH>10 AND TB1.FISH_TYPE = FISH_TYPE GROUP BY FISH_TYPE ) 
ORDER BY ID ASC