# -- 코드를 입력하세요
# SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES FROM BOOK B 
# INNER JOIN BOOK_SALES S ON (B.BOOK_ID = S.BOOK_ID)
# GROUP BY CATEGORY ORDER BY B.CATEGORY ASC
# DATE_FORMAT(S.SALES,'%Y-%m-%d') LIKE '2022-01%'

SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES FROM BOOK B, BOOK_SALES S 
WHERE B.BOOK_ID = S.BOOK_ID AND DATE_FORMAT(S.SALES_DATE,'%Y-%m-%d') LIKE '2022-01%'
GROUP BY B.CATEGORY ORDER BY B.CATEGORY 
