SELECT A.CATEGORY, B.MAX_PRICE, A.PRODUCT_NAME FROM FOOD_PRODUCT A
INNER JOIN (
SELECT PRODUCT_ID, PRODUCT_NAME,CATEGORY,PRICE, MAX(PRICE) OVER (PARTITION BY CATEGORY) AS MAX_PRICE FROM FOOD_PRODUCT) B
ON A.PRICE = B.MAX_PRICE AND A.PRODUCT_ID = B.PRODUCT_ID AND A.CATEGORY IN ('과자', '국', '김치', '식용유') ORDER BY MAX_PRICE DESC